loadedInterfaceName = "Syzygryd Lighting";

interfaceOrientation = "portrait";

pages = [[
// Syzygryd Main Interface Titlebar
{
	"name":"interfaceTitle",
	"type":"Label",
	"x":0,
	"y":0,
	"width":0.8,
	"height":.021,
	"isLocal":true,
	"value":"syzygryd lighting control",
	"align":"left",
	"color":"#000000",
	"backgroundColor":"#FF00FF",
},
{
	"name":"menuButton",
	"type":"Button",
	"x":.9,
	"y":0,
	"width":.1,
	"height":.02,
	"mode":"toggle",
	"isLocal":true,
	"ontouchstart": "if(this.value == this.max) { control.showToolbar(); } else { control.hideToolbar(); }",
	"stroke":"#FF00FF",
	"color":"#C031C7",
},
{
	"name":"menuButtonLabel",
	"type":"Label",
	"x":.9,
	"y":0,
	"width":.1,
	"height":.02,
	"isLocal":true,
	"value":"toolbar",
	"color":"#FF00FF",
},

{
	"name":"refreshButton",
	"type":"Button",
	"x":.8,
	"y":0,
	"width":.1,
	"height":.02,
	"mode":"momentary",
	"ontouchstart": "interfaceManager.refreshInterface()",
	"stroke":"#FF00FF",
	"color":"#C031C7",
},
{
	"name":"refreshButtonLabel",
	"type":"Label",
	"x":.8,
	"y":0,
	"width":.1,
	"height":.02,
	"value":"refresh",
	"color":"#FF00FF",
	
},
//Lighting Actions
{
	"name":"lightingChangeButtonLabel",
	"type":"Label",
	"x":.05,
	"y":.05,
	"width":.2,
	"height":.05,
	"isLocal":true,
	"value":"change lighting",
	"color":"#00FFFF",
},
{
	"name":"lightingChangeButton",
	"type":"Button",
	"x":.05,
	"y":.05,
	"width":.2,
	"height":.05,
	"isLocal":true,
	"mode":"momentary",
	"color":"#307D7E",
	"stroke":"#00FFFF",
},

{
	"name":"holdLightingButtonLabel",
	"type":"Label",
	"x":.25,
	"y":.05,
	"width":.2,
	"height":.05,
	"isLocal":true,
	"value":"hold lighting",
	"color":"#00FFFF",
},
{
	"name":"holdLightingButton",
	"type":"Button",
	"x":.25,
	"y":.05,
	"width":.2,
	"height":.05,
	"isLocal":true,
	"mode":"toggle",
	"color":"#307D7E",
	"stroke":"#00FFFF",
},

// Lighting Parameters

// overall light level slider
{
	"name":"lightSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.03,
	"width":.9,
	"height":.2,
	"value":"overall light level :",
	"align":"left",
	"color":"#00FFFF",
},
{
    "name":"lightSlider",
    "type":"Slider",
    "x":.05,
    "y":.15,
    "width":.9,
    "height":.05,
    "color":"#00FFFF",
    "min":0, "max":1,
    "address":"/lightIntensity",
},

// base hue speed
{
	"name":"baseHueSpeedSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.13,
	"width":.9,
	"height":.2,
	"value":"base hue speed :",
	"align":"left",
	"color":"#00FFFF",
},
{
	"name":"baseHueSpeedSlider",
	"type":"Slider",
	"x":.05,
	"y":.25,
	"width":.9,
	"height":.05,
	"color":"#00FFFF",
	"min":0, "max":1,
	"address":"/lightColor/baseHueSpeed",
},

// base hue spread
{
	"name":"baseHueSpreadSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.32,
	"width":.9,
	"height":.02,
	"align":"left",
	"value":"base hue spread :",
	"color":"#00FFFF",
},
{
	"name":"baseHueSpreadSlider",
	"type":"Slider",
	"x":.05,
	"y":.35,
	"width":.9,
	"height":.05,
	"color":"#00FFFF",
	"min":0, "max":1,
	"address":"/lightColor/baseHueSpread",
},

// base hue saturation
{
	"name":"baseHueSaturationSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.42,
	"width":.9,
	"height":.02,
	"align":"left",
	"value":"base hue saturation :",
	"color":"#00FFFF",
},
{
	"name":"baseHueSaturationSlider",
	"type":"Slider",
	"x":.05,
	"y":.45,
	"width":.9,
	"height":.05,
	"color":"#00FFFF",
	"min":0, "max":1,
	"address":"/lightColor/baseHueSaturation",
},

//base hue brightness
{
	"name":"baseHueBrightnessSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.52,
	"width":.9,
	"height":.02,
	"align":"left",
	"value":"base hue brightness :",
	"color":"#00FFFF",
},
{
	"name":"baseHueBrightnessSlider",
	"type":"Slider",
	"x":.05,
	"y":.55,
	"width":.9,
	"height":.05,
	"color":"#00FFFF",
	"min":0, "max":1,
	"address":"/lightColor/baseHueBrightness",
},

//effect tint xy
{
	"name":"tintXYLabel",
	"type":"Label",
	"x":.05,
	"y":.62,
	"width":.35,
	"height":.02,
	"align":"left",
	"value":"effect tiny xy :",
	"color":"#00FFFF",
},
{
	"name":"tint",
	"type":"MultiTouchXY",
	"bounds":[.05,.65,.35,.25],
	"maxTouches":1,
	"isMomentary":false,
	"color":"#00FFFF",
	"stroke":"00FFFF",
	"address":"/lightColor/tint",
},
//tint chroma slider
{
	"name":"tintChromaSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.9,
	"width":.35,
	"height":.04,
	"value":"chroma mod",
	"color":"#00FFFF",
},
{
	"name":"tintChromaSlider",
	"type":"Slider",
	"x":.05,
	"y":.9,
	"width":.35,
	"height":.04,
	"color":"#307D7E",
	"stroke":"#00FFFF",
	"min":0, "max":1,
	"address":"/lightColor/chroma",
},
//tint brightness slider
{
	"name":"tintBrightnessSliderLabel",
	"type":"Label",
	"x":.05,
	"y":.94,
	"width":.35,
	"height":.04,
	"value":"brightness mod",
	"color":"#00FFFF",
},
{
	"name":"tintBrightnessSlider",
	"type":"Slider",
	"x":.05,
	"y":.94,
	"width":.35,
	"height":.04,
	"color":"#307D7E",
	"stroke":"#00FFFF",
	"min":0, "max":1,
	"address":"/lightColor/brightness",
},

//Animation Parameters
//animation speed slider
{
	"name":"animationSpeedSliderLabel",
	"type":"Label",
	"x":.45,
	"y":.62,
	"width":.35,
	"height":.02,
	"align":"left",
	"value":"animation speed :",
	"color":"#FFFF00",
},
{
	"name":"animationSpeedSlider",
	"type":"Slider",
	"x":.45,
	"y":.65,
	"width":.5,
	"height":.04,
	"color":"#FFFF00",
	"min":0, "max":1,
	"address":"/lightControls/animationSpeed",
},
//animation size slider
{
	"name":"animationSizeSliderLabel",
	"type":"Label",
	"x":.45,
	"y":.695,
	"width":.35,
	"height":.02,
	"align":"left",
	"value":"animation size :",
	"color":"#FFFF00",
},
{
	"name":"animationSizeSlider",
	"type":"Slider",
	"x":.45,
	"y":.72,
	"width":.5,
	"height":.04,
	"color":"#FFFF00",
	"min":0, "max":1,
	"address":"/lightControls/animationSize",
},

//animation jitter slider
{
	"name":"animationJitterSliderLabel",
	"type":"Label",
	"x":.45,
	"y":.765,
	"width":.35,
	"height":.02,
	"align":"left",
	"value":"animation jitter :",
	"color":"#FFFF00",
},
{
	"name":"animationJitterSlider",
	"type":"Slider",
	"x":.45,
	"y":.79,
	"width":.5,
	"height":.04,
	"color":"#FFFF00",
	"min":0, "max":1,
	"address":"/lightControls/animationJitter",
},

//animation attack slider
{
	"name":"animationAttackSliderLabel",
	"type":"Label",
	"x":.45,
	"y":.835,
	"width":.35,
	"height":.02,
	"align":"left",
	"value":"animation attack :",
	"color":"#FFFF00",
},
{
	"name":"animationAttackSlider",
	"type":"Slider",
	"x":.45,
	"y":.86,
	"width":.5,
	"height":.04,
	"color":"#FFFF00",
	"min":0, "max":1,
	"address":"/lightControls/attack",
},

//animation decay slider
{
	"name":"animationDecaySliderLabel",
	"type":"Label",
	"x":.45,
	"y":.905,
	"width":.35,
	"height":.02,
	"align":"left",
	"value":"animation decay :",
	"color":"#FFFF00",
},
{
	"name":"animationDecaySlider",
	"type":"Slider",
	"x":.45,
	"y":.93,
	"width":.5,
	"height":.04,
	"color":"#FFFF00",
	"min":0, "max":1,
	"address":"/lightControls/decay",
},
]

];